### PR TITLE
Parallel processing of repo scan

### PR DESCRIPTION
**Pull request by flxo**
This patch introduces rayon to query the repos in parallel. Upon errors on the git queries the corresponding error is printed and program is *not* aborted anymore.

### CODE REVIEW

**Comment by elektronenhirn** [comment]
Hi, thanks for making it parallel: the performance boost is awesome.

On my machine (ubuntu 19.04) there is now a problem with the progress bars. They are not moving. See

https://asciinema.org/a/vhVl2AZis0POqYbm29qggJbN4

**Comment by flxo** [comment]
> On my machine (ubuntu 19.04) there is now a problem with the progress bars. They are not moving. See
> 
> https://asciinema.org/a/vhVl2AZis0POqYbm29qggJbN4

Looks like a bug in `Indicatif`. Can you try doing a single `ProgressBar::println` before the iteration?
```
diff --git a/src/model.rs b/src/model.rs
index 5a00a10..f421ad0 100644
--- a/src/model.rs
+++ b/src/model.rs
@@ -42,6 +42,8 @@ impl MultiRepoHistory {
         );
         let overall_progress = progress.add(overall_progress);
 
+        overall_progress.println(format!("Scanning {} repositories", repos.len()));
+
         thread::spawn(move || {
             progress.join_and_clear().unwrap();
         });
```

**Comment by elektronenhirn** [comment]
Sorry, for the late reply. I tested the patch but there is no visible difference.
Btw, the problem also appears on my MacBook.

**Comment by flxo** [comment]
@elektronenhirn Fixed by creating the bars with [ProgressBar::hidden](https://docs.rs/indicatif/0.12.0/indicatif/struct.ProgressBar.html#method.hidden).

**Pull request merged**
